"""Derive the rhizotron's soil ramps from Munsell soil-chart notations.

Measurement, not a test -- run by hand when the palette is being revised:

    python tests/soil_palette.py

DESIGN.md §15.2: the soil families' colours are inherited from the referent
rather than tuned by hand. Munsell soil charts are the colour system field
pedologists actually match samples against, so each family below is named by
the chips a real soil of that kind reads as, and this script turns the
notations into the Oklab literals that ship in ``rhiz_common.wgsl``. The
conversion -- Munsell renotation (illuminant C) -> XYZ -> chromatic adaptation
to D65 -> Oklab -- needs `colour-science`, which is exactly why it is an
offline instrument rather than a runtime dependency (§15.10).

Each family is a ramp: the chip a dark, humus-coated or compacted patch of
that soil reads as, and the chip its pale dry grain reads as. The shader
interpolates between the pair in Oklab, which keeps every mixture a colour
the referent could actually produce.
"""

from __future__ import annotations

import numpy as np

# (family, dark chip, light chip) -- value/chroma per the soil charts.
FAMILIES: list[tuple[str, str, str]] = [
    # Dark humic topsoil: nearly black with a warm cast.
    ("humus", "10YR 2/1", "10YR 4/2"),
    # The ordinary grey-brown of a temperate B horizon.
    ("loam", "10YR 3/2", "10YR 5/3"),
    # Ochre / loess: pale, yellow, silty.
    ("ochre", "10YR 4/4", "2.5Y 6/4"),
    # Laterite / oxidised iron: the red tropical subsoil.
    ("laterite", "2.5YR 3/4", "2.5YR 4/6"),
    # Terra rossa / red clay.
    ("red_clay", "10R 3/4", "10R 4/6"),
    # Podzolic ash grey: leached, nearly neutral.
    ("podzol", "5Y 4/1", "5Y 6/1"),
]

# And the two non-family materials the generator paints with.
EXTRAS: list[tuple[str, str]] = [
    ("stone", "5Y 6/1"),
    ("stone_dark", "5Y 4/1"),
]


def munsell_to_oklab(notation: str) -> np.ndarray:
    import colour

    xyY = colour.notation.munsell_colour_to_xyY(notation)
    xyz_c = colour.xyY_to_XYZ(xyY)
    # The Munsell renotation is specified under illuminant C; Oklab (like
    # sRGB) expects D65.
    ccs = colour.CCS_ILLUMINANTS["CIE 1931 2 Degree Standard Observer"]
    xyz = colour.adaptation.chromatic_adaptation(
        xyz_c,
        colour.xy_to_XYZ(ccs["C"]),
        colour.xy_to_XYZ(ccs["D65"]),
        method="Von Kries",
        transform="Bradford",
    )
    # The direct model function rather than the conversion graph, which needs
    # an optional dependency (networkx) this script has no other use for.
    return colour.models.XYZ_to_Oklab(xyz)


def main() -> None:
    print("// Generated by tests/soil_palette.py -- do not tune by hand.")
    print("// Munsell soil-chart chips, illuminant C -> D65 (Bradford), Oklab.")
    for name, dark, light in FAMILIES:
        lo = munsell_to_oklab(dark)
        hi = munsell_to_oklab(light)
        print(
            f"// {name}: {dark} -> {light}\n"
            f"vec3<f32>({lo[0]:.4f}, {lo[1]:.4f}, {lo[2]:.4f}), "
            f"vec3<f32>({hi[0]:.4f}, {hi[1]:.4f}, {hi[2]:.4f}),"
        )
    for name, chip in EXTRAS:
        lab = munsell_to_oklab(chip)
        print(
            f"// {name}: {chip}\n"
            f"vec3<f32>({lab[0]:.4f}, {lab[1]:.4f}, {lab[2]:.4f})"
        )


if __name__ == "__main__":
    main()
