// The rhizotron's image: soil and roots, seen through the pane -- §15.2.
//
// Every pixel is material. Where the fungal compositors shade luminous
// density against a void, this pass paints the matrix itself: stratum colour
// from Munsell soil-chart ramps, stones, fine static grain, and moisture
// darkening the whole of it -- wet soil is darker and slightly more
// saturated, which is the most familiar material appearance there is. Over
// the matrix, the roots: coverage from the structure field through a
// steep-but-C1 transfer whose crispness is a measured licence (§15.7.2),
// coloured pale ivory at the living front and browning toward the soil with
// age -- the eye led to the growing edge by the same gradient the biology
// provides.
//
// The descent arrives here as `base_row`: where the top of the window sits in
// the texture this frame, in fractional rows, interpolated between the last
// two ticks. The simulation scrolls in exact integer rows (rhiz_moisture);
// the presentation glides over it at the sub-row remainder, so the sinking is
// continuous at any frame rate. The vertical axis never wraps -- the margins
// above and below the view are real generated soil, which is what makes the
// sub-row sampling at the extremes honest rather than a wraparound artefact.
//
// Every mapping is a smooth transfer, as everywhere else: no thresholds, and
// nothing anywhere is a function of the clock.

//!include rhiz_common.wgsl

//!struct RenderParams

@group(0) @binding(0) var<storage, read> rp: RhizParams;
@group(0) @binding(1) var<storage, read> render: RenderParams;
@group(0) @binding(2) var moisture_tex: texture_2d<f32>;
@group(0) @binding(3) var structure_tex: texture_2d<f32>;
@group(0) @binding(4) var hdr_out: texture_storage_2d<rgba16float, write>;
@group(0) @binding(5) var samp: sampler;
@group(0) @binding(6) var record_tex: texture_2d<f32>;

// The soil families, as ramps between two Munsell soil-chart chips in Oklab.
// Generated by tests/soil_palette.py (illuminant C -> D65, Bradford) -- the
// gamut is inherited from the referent rather than tuned by hand (§15.2).
// The chart chips are far brighter than this application's ground, so the
// shading keeps each chip's *chromatic identity* and re-anchors its lightness
// into the dark-earth envelope below.
const FAMILY_COUNT: u32 = 6u;

fn family_dark(i: u32) -> vec3<f32> {
    switch i {
        case 0u: { return vec3<f32>(0.3132, 0.0073, 0.0139); } // humus 10YR 2/1
        case 1u: { return vec3<f32>(0.4014, 0.0123, 0.0304); } // loam 10YR 3/2
        case 2u: { return vec3<f32>(0.4920, 0.0204, 0.0617); } // ochre 10YR 4/4
        case 3u: { return vec3<f32>(0.4057, 0.0474, 0.0410); } // laterite 2.5YR 3/4
        case 4u: { return vec3<f32>(0.4065, 0.0548, 0.0343); } // red clay 10R 3/4
        default: { return vec3<f32>(0.4891, 0.0005, 0.0187); } // podzol 5Y 4/1
    }
}

fn family_light(i: u32) -> vec3<f32> {
    switch i {
        case 0u: { return vec3<f32>(0.4906, 0.0120, 0.0334); } // 10YR 4/2
        case 1u: { return vec3<f32>(0.5796, 0.0158, 0.0471); } // 10YR 5/3
        case 2u: { return vec3<f32>(0.6653, 0.0071, 0.0672); } // 2.5Y 6/4
        case 3u: { return vec3<f32>(0.4972, 0.0635, 0.0618); } // 2.5YR 4/6
        case 4u: { return vec3<f32>(0.4982, 0.0732, 0.0521); } // 10R 4/6
        default: { return vec3<f32>(0.6641, -0.0005, 0.0194); } // 5Y 6/1
    }
}

// Stone: leached ash-grey, 5Y 4/1 -> 5Y 6/1.
const STONE_DARK: vec3<f32> = vec3<f32>(0.4891, 0.0005, 0.0187);
const STONE_LIGHT: vec3<f32> = vec3<f32>(0.6641, -0.0005, 0.0194);

// The Munsell chips above span roughly this much Oklab L; a chip's position
// in that span is what survives the re-anchoring into the dark ground.
const CHIP_L_LO: f32 = 0.30;
const CHIP_L_SPAN: f32 = 0.37;

@compute @workgroup_size(8, 8, 1)
fn main(@builtin(global_invocation_id) gid: vec3<u32>) {
    if (gid.x >= render.out_w || gid.y >= render.out_h) {
        return;
    }
    let uv = (vec2<f32>(gid.xy) + 0.5)
        / vec2<f32>(f32(render.out_w), f32(render.out_h));

    // Lateral aspect correction samples more (or less) of the wrapping x
    // axis; the vertical axis maps the view rows exactly, margins excluded.
    let ux = fract((uv.x - 0.5) * rp.x_span + 0.5);
    let row = rp.base_row + uv.y * f32(rp.view_rows);
    let suv = vec2<f32>(ux, row / f32(rp.dims_y));

    // The wetness the eye sees is the EMA channel: the moisture field's own
    // dynamics, lowpassed once more on the way to luminance.
    let wet_raw = textureSampleLevel(moisture_tex, samp, suv, 0.0).y;
    let wet = 1.0 - exp(-1.6 * clamp(finite_or(wet_raw, 0.0), 0.0, 1.5));

    let soil = soil_at(rp, ux, row);

    // --- Which soil this is ------------------------------------------------
    // The palette macro walks the family ring: the anchor (plus the same slow
    // autonomous drift the fungal hue has) picks a position among the six
    // families, and neighbouring families blend. The stratum then moves the
    // texel along its family's dark-to-pale ramp.
    let fpos = fract(render.hue_global / TAU) * f32(FAMILY_COUNT);
    let f0 = u32(floor(fpos)) % FAMILY_COUNT;
    let f1 = (f0 + 1u) % FAMILY_COUNT;
    let ft = fract(fpos);
    let dark = mix(family_dark(f0), family_dark(f1), ft);
    let light = mix(family_light(f0), family_light(f1), ft);
    var chip = mix(dark, light, soil.light);

    // Stones sit in the matrix as their own material -- but half-buried in
    // it, not resting on top: the chip is pulled a third of the way toward
    // the surrounding soil and its chroma dulled, because full-strength
    // olive-grey discs against warm earth read as a field of pale dots --
    // and a field of dots is §4.7's geometry whatever it is made of.
    var stone_chip = mix(STONE_DARK, STONE_LIGHT, 0.5 + 0.5 * soil.grain);
    stone_chip = vec3<f32>(stone_chip.x, stone_chip.yz * 0.8);
    stone_chip = mix(stone_chip, chip, 0.62);
    chip = mix(chip, stone_chip, clamp(soil.stone, 0.0, 1.0));

    // --- Into the visible-earth envelope (§17.5) ----------------------------
    // The chip's position in the chart's lightness span becomes its position
    // in [background + floor, background + floor + range]; its chromatic
    // direction comes with it, eased down as the lightness drops so a dim
    // texel is a dimmer version of the same soil rather than a neon one.
    // The floor is §17.1's fix: every soil texel clears the void's black, so
    // the ground is the mid of this image and the sky above it is the dark.
    let t_chip = clamp((chip.x - CHIP_L_LO) / CHIP_L_SPAN, 0.0, 1.0);
    var l = render.background_luma + rp.soil_l_floor + rp.soil_l_range * t_chip;
    var ab = chip.yz * pow(max(l, 1e-4) / max(chip.x, 1e-4), 0.7);

    // Moisture: darker and slightly richer. This is the weather made visible,
    // and the slew limiter downstream is what ultimately bounds its pace.
    l = l * (1.0 - rp.wet_darken * wet);
    ab = ab * (1.0 + rp.wet_chroma * wet);

    // Fine grain, static in world space: texture, not noise -- and quieter
    // inside stones, which are smoother material than the earth around them.
    l = l + soil.grain * rp.grain_amount * 0.009 * (1.0 - 0.8 * soil.stone);

    // Ghost strata (§17.6): where past seasons stand in the ground --
    // darker, quieter earth in the shape of the interred skeletons. Read
    // before the roots so the living and the wood shade *over* their
    // ancestors, at rungs measured from the haunted ground itself.
    let ghost = max(finite_or(
        textureSampleLevel(record_tex, samp, suv, 0.0).w, 0.0), 0.0);
    let ghost_sat = ghost / (ghost + 0.12);
    l = l - 0.055 * ghost_sat;
    ab = ab * (1.0 - 0.30 * ghost_sat);

    // --- The roots: one silhouette, two materials (§17.5, §17.6) -----------
    // The living layer and the record are one organism, so they share one
    // coverage: combined mass through the saturating map, with the edge
    // sharpening from `root_edge` toward `wood_edge` as material commits --
    // wood is crisper than fuzz. Splitting the silhouette between two knees
    // was tried first and opened a hand-over gap: mass mid-transfer sat
    // below both, and roots dissolved into dashes exactly where they were
    // becoming permanent. One silhouette cannot gap; wood-ness is a colour
    // axis along it, not a second figure.
    let root = textureSampleLevel(structure_tex, samp, suv, 0.0);
    let rec = textureSampleLevel(record_tex, samp, suv, 0.0);
    let density = max(finite_or(root.x, 0.0), 0.0);
    let lignin = max(finite_or(rec.x, 0.0), 0.0);
    let mass = density + lignin;
    let wood_frac = lignin / max(mass, 1e-5);
    let saturated = mass / (mass + max(rp.root_knee, 1e-4));
    let edge = mix(rp.root_edge, rp.wood_edge, wood_frac);
    let coverage = smoothstep(0.5 - edge, 0.5 + edge, saturated);
    let age = max(finite_or(root.y, 0.0), 0.0);
    let young_f = exp(-age / max(rp.root_age_scale * 0.4, 1.0));
    let wood_age = max(finite_or(rec.y, 0.0), 0.0);
    let mature = 1.0 - exp(-wood_age / max(rp.wood_age_scale, 1.0));
    // A pallor boost over the shared macro: the visible-earth envelope
    // (§17.5) lifted the ground, and the living material keeps its two
    // rungs of headroom above the palest stratum.
    let l_young = clamp(
        render.background_luma + render.filament_luma * 1.3, 0.0, render.l_max);

    // Root hairs, and the mycorrhizal accent (§15.2): the transfer's soft
    // skirt, re-admitted only around *young* material -- a halo of pale fuzz
    // at the growing front that fades as the root lignifies. Where the
    // material is young *and fine*, the same skirt carries a faint cool
    // shimmer: the hyphae, the one cool accent in a warm field, spending the
    // chroma budget and none of the luminance budget beyond the hairs'.
    let skirt = smoothstep(0.04, 0.5, saturated) * (1.0 - coverage);
    let hair = skirt * young_f;
    l = mix(l, l_young, hair * rp.root_hair * 0.5);
    let fineness = clamp(finite_or(root.z, 0.0), 0.0, 1.0);
    let shimmer = hair * fineness * rp.mycorrhiza;
    ab = ab + vec2<f32>(-0.010, -0.024) * shimmer;

    if (coverage > 1e-4) {
        // Fine material browns on a much shorter clock than coarse: fuzz is
        // pale only while it is actually growing, so the churn of dying
        // fines reads as breathing ground rather than as pale confetti
        // lingering minutes after the life has left it.
        let age_scale = max(rp.root_age_scale, 1.0)
            * (1.0 - 0.55 * fineness * fineness);
        let brown = (1.0 - exp(-age / age_scale)) * rp.root_brown;
        // Warm ivory: a faint 10YR-ish cast so young roots sit in the soil's
        // own colour world rather than reading as neutral grey.
        let young = vec3<f32>(l_young, 0.010 * l_young / 0.4, 0.045 * l_young / 0.4);
        // The living gradient hands over to the record's: ivory browns
        // toward new wood -- russet, two rungs above the ground -- and wood
        // matures from russet down to an umber a shade beneath it, shaded
        // by biographical age, the channel nothing resets. One continuous
        // path down each root's length: tip, tan, russet, umber.
        let russet = vec3<f32>(
            l + 0.055, ab + vec2<f32>(0.006, 0.014));
        let umber = vec3<f32>(
            max(l - 0.05, render.background_luma), ab * 0.92);
        let wood_lab = mix(russet, umber, mature);
        let living_lab = mix(young, russet, brown);
        let root_lab = mix(living_lab, wood_lab, wood_frac);
        l = mix(l, root_lab.x, coverage);
        ab = mix(ab, root_lab.yz, coverage);
    }

    // --- The sky (§17.4) ----------------------------------------------------
    // Above the soil line the pane is open air: the darkest thing in the
    // image, faintly cool so the earth below reads warm. The blend eases
    // over a couple of rows -- the litter line, where humus meets light --
    // and takes the root layer with it (hairs may skirt a row above the
    // line; nothing may glow in the sky).
    let depth = row - rp.surface_row;
    let airf = 1.0 - smoothstep(-0.5, 2.0, depth);
    // The litter line: a thin pale seam of surface debris where humus meets
    // air, textured by the grain so it reads as material, not as a rule.
    let seam = smoothstep(-0.3, 0.6, depth) * (1.0 - smoothstep(0.6, 3.0, depth));
    l = l + seam * (0.045 + 0.03 * soil.grain);
    let sky_l = render.background_luma * 0.85;
    l = mix(l, sky_l, airf);
    ab = mix(ab, vec2<f32>(-0.002, -0.008), airf);

    // The same perceptual bounds the fungal compositors respect; the safety
    // stage re-applies both to its target, so these are shaping, not the
    // guarantee.
    l = clamp(l, 0.0, render.l_max);
    let chroma = length(ab);
    if (chroma > 1e-6) {
        let bounded = clamp(chroma, render.chroma_floor, render.c_max);
        ab = ab * (bounded / chroma);
    }

    let rgb = oklab_to_linear_srgb(vec3<f32>(l, ab));
    textureStore(
        hdr_out, vec2<i32>(gid.xy), finite_or4(vec4<f32>(rgb, 1.0), 0.0));
}
